name = "GDAL"
uuid = "add2ef01-049f-52c4-9ee2-e494f65e021a"
keywords = ["GDAL", "IO"]
license = "MIT"
desc = "Wrapper for GDAL - Geospatial Data Abstraction Library"
version = "1.1.4"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
GDAL_jll = "a7073274-a066-55f0-b90d-d619367d196c"
MozillaCACerts_jll = "14a3606d-f60d-562e-9121-12d972cd8159"
PROJ_jll = "58948b4f-47e0-5654-a9ad-f609743f8632"

[compat]
CEnum = "0.2, 0.3, 0.4"
GDAL_jll = "3.0.4"
MozillaCACerts_jll = ">= 2020"
PROJ_jll = "7.0.1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
