name = "GDAL"
uuid = "add2ef01-049f-52c4-9ee2-e494f65e021a"
keywords = ["GDAL", "IO"]
license = "MIT"
desc = "Wrapper for GDAL - Geospatial Data Abstraction Library"
version = "1.11.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
GDAL_jll = "a7073274-a066-55f0-b90d-d619367d196c"
NetworkOptions = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
PROJ_jll = "58948b4f-47e0-5654-a9ad-f609743f8632"

[compat]
CEnum = "0.2, 0.3, 0.4, 0.5"
GDAL_jll = "303.1100.100"
NetworkOptions = "1.2"
PROJ_jll = "902"
julia = "1.9"
